# Generated by Django 5.1 on 2024-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_user_agreed_on',
            field=models.BooleanField(default=False),
        ),
    ]
