# Generated by Django 5.1 on 2024-09-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_date_user_agreed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_user_agreed_on',
            new_name='user_agreement',
        ),
    ]
