# Generated by Django 5.1 on 2024-09-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_date_user_agreed_on_customuser_user_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_agreement',
            new_name='acceptTerms',
        ),
    ]
