# Generated by Django 5.1 on 2024-09-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('Innovative Methods', 'Innovative Methods'), ('Skills', 'Skills'), ('Learning Paths', 'Learning Paths'), ('Technology Tools', 'Technology Tools'), ('Robotics Trends', 'Robotics Trends'), ('Industry Benefits', 'Industry Benefits'), ('Course Selection', 'Course Selection'), ('Interactive Learning', 'Interactive Learning'), ('Certification Impact', 'Certification Impact'), ('Domain News', 'Domain News')], default=0, max_length=100),
        ),
    ]
