# Generated by Django 5.1 on 2024-09-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('pdf', 'PDF'), ('webinar', 'Webinar'), ('others', 'Others')], default='article', max_length=50)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False, help_text='Accessible to everyone for free.')),
                ('is_demo', models.BooleanField(default=False, help_text='Accessible to everyone as a demo resource.')),
                ('minimum_subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
