# Generated by Django 5.1 on 2024-09-18 11:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_content_file_remove_resource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
        ),
    ]
