# Generated by Django 5.1 on 2024-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_chapter_slug_lesson_slug_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
