# Generated by Django 5.1 on 2024-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
        ),
    ]
