# Generated by Django 5.1 on 2024-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
